### ISSUE TITLE
Multiple tracked flips have the uId "1"

### ISSUE THREAD

**Issue by matthias-luger** [Coflnet/SkyFlipTracker#83]
Multiple tracked flips in one response have the uId "1". Is this expected? I currently use it as a key for react to identify them, which causes re-rendering issues. 
![grafik](https://github.com/user-attachments/assets/fb0be39a-d172-4750-bb04-b3a0c229dfd7)

**Comment by Ekwav** [comment]
Thats the case for flips that were not listed on ah (also soldAuction all 0) the uid is a short version of the soldAuction currently.
You would want to identify tracked flips by their sellTime, you can optionally add the uid in case two items sell in the same second (unlikely but possible)

Generally using the time would also make it easier to find the flip again as they are ordered by time anyways.

**Comment by matthias-luger** [comment]
fixed by https://github.com/Coflnet/hypixel-react/pull/1313
